var rule = {
  title: '55影院',
  host: 'https://www.55tv.net',
  class_name: '电影&电视剧&综艺&动漫',
  class_url: '1&2&4&3',
  searchUrl: '/search',
  searchable: 2,
  quickSearch: 0,
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  url: '/vodlist/fyclass?catid=0&type=&area=&year=&page=fypage',
  filterable: 0,
  filter_url: '',
  filter: {},
  filter_def: {},
  detailUrl: '/index.php/vod/detail/id/fyid.html',
  play_parse: true,
  lazy: "js:\n  let html = request(input);\n  let hconf = html.match(/r player_.*?=(.*?)</)[1];\n  let json = JSON5.parse(hconf);\n  let url = json.url;\n  if (json.encrypt == '1') {\n    url = unescape(url);\n  } else if (json.encrypt == '2') {\n    url = unescape(base64Decode(url));\n  }\n  if (/\\.(m3u8|mp4|m4a|mp3)/.test(url)) {\n    input = {\n      parse: 0,\n      jx: 0,\n      url: url,\n    };\n  } else {\n    input = url && url.startsWith('http') && tellIsJx(url) ? {parse:0,jx:1,url:url}:input;\n  }",
  limit: 6,
  推荐: '.vodlist;a&&title;img&&data-src;img&&Text;a&&href',
  一级: '.cover;a&&title;img&&data-src;img&&Text;a&&href',
  二级: {
    title: 'h1&&Text;.slide-info:eq(2)--strong&&Text',
    img: '.cover&&img&&data-src',
    desc: '.date.areayear&&Text;.date.areayear&&span:eq(1)&&Text;.date.areayear&&span:eq(2)&&Text;.date.leadingactorrow&&Text;.date.directorrow&&Text',
    content: '.des&&Text',
    tabs: '.hd h4',
    tab_text: 'body&&Text',
    lists: '.playgroup&&ul:eq(#id) li',
  },
  搜索: '*',
  tab_exclude:'热门播放|最近更新|猜你喜欢',
}