var rule = {
  title:'西瓜影院',
  host:'https://www.a6club.com/',
  url:'/index.php/vod/show/id/fyclass/page/fypage.html',
  searchUrl:'/index.php/vod/search/page/fypage/wd/**.html',
  class_name: '电影&电视剧&综艺&动漫&B站',
  class_url: '20&37&45&43&47',
  searchable: 2,
  quickSearch: 0,
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  filterable: 0,
  filter_url: '',
  filter: {},
  filter_def: {},
  detailUrl: '/index.php/vod/detail/id/fyid.html',
  play_parse: true,
  lazy: "js:\n  let html = request(input);\n  let hconf = html.match(/r player_.*?=(.*?)</)[1];\n  let json = JSON5.parse(hconf);\n  let url = json.url;\n  if (json.encrypt == '1') {\n    url = unescape(url);\n  } else if (json.encrypt == '2') {\n    url = unescape(base64Decode(url));\n  }\n  if (/\\.(m3u8|mp4|m4a|mp3)/.test(url)) {\n    input = {\n      parse: 0,\n      jx: 0,\n      url: url,\n    };\n  } else {\n    input = url && url.startsWith('http') && tellIsJx(url) ? {parse:0,jx:1,url:url}:input;\n  }",
  limit: 6,
  推荐: '.movie-list-body.flex;.movie-title&&Text;.movie-post-lazyload&&data-original;.movie-rating&&Text;a&&href',
  一级: '.movie-list-item;.movie-title&&Text;.movie-post-lazyload&&data-original;.movie-rating&&Text;a&&href',
  二级: {
    title: '.movie-title&&Text;.cr3&&Text',
    img: '.poster&&img&&src',
    desc: '.scroll-content&&Text;.scroll-content&&a:eq(3)&&Text;.scroll-content&&a:eq(4)&&Text;.cr3.starLink&&Text',
    content: '.detailsTxt&&Text',
    tabs: '.play_source_tab&&a',
    tab_text: 'a--span&&Text',
    lists: '.content_playlist:eq(#id) li',
  },
  搜索: '.vod-search-list;.movie-title&&Text;.movie-post-lazyload&&data-original;.movie-rating&&Text;a&&href',
}